---
surname: Mark Fransham
position: "Senior Departmental Research Lecturer in Quantitative Methods"
address: "Dept of Social Policy & Intervention, University of Oxford, 32 Wellington Square, Oxford OX1 2ER"
phone: +44 (0)1865 270352
www: mfransham.github.io
email: mark.fransham@spi.ox.ac.uk
headcolor: "414141"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Current positions

**Senior Departmental Research Lecturer in Quantitative Methods** \hfill Jul 2022 -           
Department of Social Policy & Intervention, University of Oxford 

**Research Fellow** \hfill Apr 2023 -            
Wolfson College, University of Oxford 

**Visiting Fellow** \hfill Oct 2020 -           
International Inequalities Institute, London School of Economics & Political Science

**Fellow** \hfill Aug 2023 -           
World Inequality Lab, Paris School of Economics

# Previous positions

**Senior Research Officer** \hfill Jan 2021 - Jun 2022      
Department of Social Policy & Intervention, University of Oxford 

**Departmental Lecturer in Quantitative Methods** \hfill Sep 2020 - Jun 2022          
Department of Social Policy & Intervention, University of Oxford 

**Junior Research Fellow** \hfill Oct 2020 - Apr 2023            
Wolfson College, University of Oxford 

**Research Officer** \hfill 2018-2020       
International Inequalities Institute, London School of Economics & Political Science

**Social Statistics Officer** \hfill 2007-2016       
Oxford City Council

**Policy Officer (Social Inclusion & Health Inequalities)** \hfill 2005-2007       
Oxford City Council

**Cancer Information Analyst** \hfill 2004-2005       
Oxford Cancer Intelligence Unit, National Health Service

**Research & Evaluation Officer** \hfill 2002-2004       
Nacro

# Education

**DPhil in Geography & the Environment** \hfill 2015-2018       
School of Geography & the Environment, University of Oxford           
Thesis title: *Understanding neighbourhood income poverty dynamics in England*        
Supervisors: Professor Danny Dorling and Dr Rachel Loopstra        
Passed without corrections        

**MSc Applied Social Studies / Diploma in Social Work** \hfill 2000-2002        
Department of Social Policy and Social Work, University of Oxford

**BA Hons Physics 2:1** \hfill 1995-1998        
St Catherine’s College, University of Oxford

\newpage

# Publications

## Works in progress

Bukowski, P., Fransham, M., Lee N. et al. (in preparation) Trends in spatial labour income inequality in Canada, France, Germany, UK and the US 1975‑2020: the Linking National and Regional Inequalities project. 

Fransham, M., Bauluz, L., Breau, S., Lee, N. & Verdugo, G., (in preparation) International trends in geographic income inequality: a method for assessing the comparability of spatial units.  

## Peer-reviewed articles

Hilhorst, S., Koch, I., Fransham, M., Reeves, A. & Savage, M. (accepted, in press) ‘Corruption talk’ and working-class politics in 21st century Britain. *The Sociological Review*. 

Reeves, A., Fransham, M., Stewart, K., Reader, M., & Patrick, R. (2024). Capping welfare payments for workless families increases employment and economic inactivity: Evidence from the UK's benefit cap. *International Journal of Social Welfare*, 1–14. https://doi.org/10.1111/ijsw.12651

Lee, N., Fransham, M. & Bukowski, P. (2024) Spatial Labour Market Inequality and Social Protection in the UK. *LSE Public Policy Review*, 3(2), 1–11. https://doi.org/10.31389/lseppr.99   

Fransham, M., Herbertson, M., Pop, M., Bandeira Morais, M., & Lee, N. (2023). Level best? The levelling up agenda and UK regional inequality. *Regional Studies*, 57(11), 2339–2352. https://doi.org/10.1080/00343404.2022.2159356

Reeves, A., Fransham, M., Stewart, K., & Patrick, R. (2022). Does capping social security harm health? A natural experiment in the UK. *Social Policy & Administration*, 56(3), 345–359. https://doi.org/10.1111/SPOL.12768 ([Guardian](https://www.theguardian.com/commentisfree/2021/oct/03/universal-credit-cut-will-risk-the-health-of-millions) | [New Psychotherapist](https://www.psychotherapy.org.uk/media/otzimjco/79-new-psychotherapist-winter-spring-2022.pdf))

Koch, I., Fransham, M., Cant, S., Ebrey, J., Glucksberg, L., & Savage, M. (2020). Social Polarisation at the Local Level: A Four-Town Comparative Study on the Challenges of Politicising Inequality in Britain, *Sociology*, 55(1), 3–29. https://doi.org/10.1177/0038038520975593 (winner of [2022 SAGE Prize for Innovation/Excellence](https://www.britsoc.co.uk/opportunities/sage-prize-for-innovationexcellence/))

Fransham, M. (2020) Neighbourhood gentrification, displacement, and poverty dynamics in post-recession England, *Population, Space and Place*, 25(5):e2327.  https://doi.org/10.1002/psp.2327 

Fransham, M. (2019) Increasing evenness in the neighbourhood distribution of income poverty in England 2005–2014: Age differences and the influence of private rented housing, *Environment and Planning A: Economy and Space* 51(2), 403–419. https://doi.org/10.1177/0308518X18792569 

Fransham, M. (2019) Income and Population Dynamics in Deprived Neighbourhoods: Measuring the Poverty Turnover Rate Using Administrative Data, *Applied Spatial Analysis and Policy* 12(2), 275-300. https://link.springer.com/article/10.1007/s12061-017-9242-6 

## Working papers, book chapters and other publications

Fransham, M., Andersen, K., Patrick, R., Reeves, A., Stewart, K. (2024). *Capped and trapped (in the UK's housing market): how the benefit cap makes it almost impossible to find affordable housing*. Working Paper CASE/234, Centre for Analysis of Social Exclusion, London School of Economics & Political Science. https://sticerd.lse.ac.uk/dps/case/cp/casepaper234.pdf

Koch I, Fransham M, Cant S, Ebrey J, Glucksberg L, Savage M. (2023) The Challenges of Polarisation: Lessons for (Re-)Politicising Inequality across Four English Towns. In: Gohrisch J, Stedman G (eds.) *Affective Polarisation: Social Inequality in the UK after Austerity, Brexit and COVID-19*. Bristol: Bristol University Press.

Bauluz, L, Bukowski, P , Fransham, M , Lee, A, López Forero, M, Novokmet, F, Breau, S, Lee, N , Malgouyres, C, Schularick, M & Verdugo, G (2023) Spatial wage inequality in North America and Western Europe: changes between and within local labour markets 1975-2019. Working Paper (98). International Inequalities Institute, London School of Economics & Political Science, London, UK. https://eprints.lse.ac.uk/119922/

Fransham, M. (2023). Poverty. In D. Demeritt & L. Lees (Eds.), *Concise Encyclopedia of Human Geography*. Cheltenham: Edward Elgar.

Reeves, A., Fransham, M., Stewart, K., & Patrick, R. (2021). *Does capping social security harm health? A natural experiment in the UK*. Working Paper CASE/221, Centre for Analysis of Social Exclusion, London School of Economics & Political Science. https://sticerd.lse.ac.uk/dps/case/cp/casepaper221.pdf

Koch, I., Fransham, M., Cant, S., Ebrey, J., Glucksberg, L. and Savage, M. (2019) *Social polarisation at the local level: a four-town comparative study*. Working Paper (37). International Inequalities Institute, London School of Economics & Political Science, London, UK. http://eprints.lse.ac.uk/102216/

Fransham, M., & Dorling, D. (2018). Homelessness and Public Health. *British Medical Journal*, 360, k214. https://doi.org/10.1136/bmj.k214 

Fransham, M., & Dorling, D. (2017). Have mortality improvements stalled in England? *British Medical Journal*, 1946, j1946. http://doi.org/10.1136/bmj.j1946

Fransham, M., & Dorling, D. (2017, April 8). Oxford academics: “House prices can keep rising only if the Government backs mass buy-to-let.” *The Telegraph*. London.

# Funding

**ESRC Open Research Area 6** \hfill 2021-2025        
*Linking National and Regional Income Inequality: Cross-Country Data Harmonization and Analysis*       
Co-Investigator with partners at LSE, McGill, Bonn and Paris-Saclay universities        
Total ESRC funding £458,480; total project funding approx £1.2 million; grant number ES/V013548/1

**3 year joint ESRC/EPSRC doctoral studentship** \hfill 2015-2018       
Social Sciences Doctoral Training Centre, University of Oxford        
Grant numbers ES/J500112/1, EP/K503113/1, EP/L505031/1, EP/M50659X/1

# Awards

**Divisional Teaching Excellence Award (Early Career Strand)** \hfill Jun 2022    
Social Sciences Division, University of Oxford

**Winner of SAGE Prize for Innovation/Excellence in the journal Sociology** \hfill Apr 2022    
*Awarded for Koch, Fransham et al. (2020)*    
British Sociological Association

# Teaching experience

## Current teaching at University of Oxford

**BA Philosophy, Politics and Economics / History & Politics / Human Sciences**        
Social Policy 224 option: poverty

**MSc/MPhil Evidence-Based Social Intervention and Policy Evaluation**       
Quantitative Analysis module convenor            
Evaluation Methods module: matching methods, synthetic control, difference-in-differences, regression discontinuity, interrupted time series, meta-analysis        
Social Policy Analysis module       
Thesis supervision        

**MSc/MPhil Comparative Social Policy**       
Social Policy Analysis module       
Thesis supervision        

**DPhil (PhD) Social Policy / Social Intervention & Policy Evaluation**       
DPhil co-supervision: Dan Mocanu (2023-)       
Methods Hub (methods advice and guidance on training opportunities)      
Convenor of *Modern Methods in Social Policy and Intervention Research* seminar series        
Methods Meetups (methods workshops)   

## Past teaching

**London School of Economics Masterclass** *Inequality and Social Cohesion: A Global Perspective* \hfill July 2019        
Fundacion Ramon Areces, Madrid 

**MSc Inequalities and Social Science, London School of Economics**  \hfill 2018-2020        
Dissertation supervision

**BA Philosophy, Politics and Economics, University of Oxford** \hfill 2017-2019       
Social Policy 224 undergraduate option (2017-2019, as a college tutor)

**BA Geography, University of Oxford** \hfill 2017        
Applied Statistics module (as teaching assistant)

# Leadership, service and affiliations

## Advisory positions

Government Statistical Service Migration Statistics Expert Group \hfill 2020-current 		
UK Population Theme Advisory Board, Office for National Statistics \hfill 2016-current 		
Member of Council, British Society for Population Studies \hfill 2019-2023 		
Local Authority Co-Chair, Local Government Association CLIP Population Subgroup \hfill 2013-2015	
Official Statistics Committee, Royal Statistical Society \hfill 2012-2014       
Chair, Oxfordshire Data Observatory \hfill 2008-2010	

## Peer review

Economic & Social Research Council (ESRC) Peer Review College member (2024-current). Reviewer for Arts & Humanities Research Council (AHRC), *Journal of the Royal Statistical Society Series A*, *Social Science & Medicine*, *SSM - Population Health*, *Cambridge Journal of Regions, Economy & Society*, *Regional Studies*, *BMJ Open*, *Journal of Social Policy*, *Urban Studies* and *Population, Space and Place*.

## Administrative service

Chair of Examiners, Department of Social Policy & Intervention, University of Oxford \hfill 2024-current    
Graduate Studies Committee, Department of Social Policy & Intervention, University of Oxford \hfill 2023-current   
Ethics Committee, Department of Social Policy & Intervention, University of Oxford \hfill 2021-current        
MSc Teaching Committees, Department of Social Policy & Intervention, University of Oxford \hfill 2020-current        
IT Committee, Department of Social Policy & Intervention, University of Oxford \hfill 2021-2023    
Research Committee, International Inequalities Institute, London School of Economics  \hfill 2019-2010        
Equality and Diversity Committee, School of Geography & the Environment, University of Oxford \hfill 2015-2017         
\hspace*{1cm} (Contributed to the successful application for an Athena SWAN Bronze Award)     

## Professional membership

Royal Statistical Society (2010-), British Society for Population Studies (2014-), Social Policy Association (2017-) and Regional Studies Association (2018-)
